### ISSUE TITLE
private repos are not retrieved?

### ISSUE THREAD

**Issue by jotadepicas** [freeall/dependency-hunter#7]
Hi, it seems only the public repos of my organization are being retrieved, but not the private ones.
Is this an expected behavior or a bug?

thanks!

**Comment by freeall** [comment]
Hmm, it should be both. And I'm quite sure it has been before. But now that I test it it seems to not do that.

Maybe something has changed in the github api

**Comment by jotadepicas** [comment]
Yep, so it seems 😢 .
Btw, thank you so much for the quick reply!

**Comment by eagleeye** [comment]
@freeall @jotadepicas  check my solution
